trigger:
- main

jobs:
- job: BuildUbuntu
  pool:
    vmImage: ubuntu-latest
  steps:
  - bash: |
      sudo apt-get update
      sudo apt-get -y install build-essential
      sudo apt-get -y install curl git
      sudo apt-get -y install libcurl4-openssl-dev
      sudo apt-get -y install libssl-dev
      sudo apt-get -y install rapidjson-dev
    displayName: apt-get installs
  - bash: cmake --version
    displayName: check cmake
  - bash: |
      mkdir tmp && cd tmp && mkdir gtest && cd gtest
      git clone --depth 1 --branch release-1.12.0 https://github.com/google/googletest.git
      cd googletest
      mkdir build && cd build
      cmake ..
      make
      sudo make install
    displayName: install GTest
  - bash: |
      cd tmp && mkdir softhsm && cd softhsm
      git clone --depth 1 --branch 2.6.1 https://github.com/opendnssec/SoftHSMv2.git
      cd SoftHSMv2
      ./configure
      make
      sudo make install
    displayName: install SoftHSM
